name: Publish

permissions:
  contents: write
  
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.115

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="LighthouseNotes-Server-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish Server.csproj --framework net7.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name" --self-contained false 

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"
      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "Server.csproj"
          version: bump-build

      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
          git push

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "LighthouseNotes-Server-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
